---
- name: install trac
  apt:
    name: trac
    state: installed
  tags:
    - trac

- include: "{{ item }}"
  with_items:
    - base_config.yml
    - instances.yml
    - plugins.yml
  tags:
    - trac
